// @generated by tools/gen_known_services.py - DO NOT EDIT BY HAND.
//
// Source: AdventDevInc/kudu, src/shared/service-safety-kb.ts (MIT licence).
// Upstream: https://github.com/AdventDevInc/kudu
// See THIRD_PARTY_NOTICES.md for the attribution and the licence text.
//
// What this is for: a service Windows itself ships should not be reported merely
// because its image is unsigned, unreadable or absent. Those are normal states for a
// system service, and reporting them buries the services that are genuinely worth
// looking at.
/// One Windows service that Windows itself ships.
pub struct KnownService {
    pub name: &'static str,
    /// `safe` (commonly disabled without issues), `caution`, or `unsafe`
    /// (system-critical).
    pub safety: &'static str,
    pub category: &'static str,
    pub note: &'static str,
}

/// 70 entries, sorted by service name.
pub static KNOWN_SERVICES: &[KnownService] = &[
    KnownService {
        name: "bfe",
        safety: "unsafe",
        category: "security",
        note: "Base Filtering Engine — required by firewall",
    },
    KnownService {
        name: "bits",
        safety: "unsafe",
        category: "core",
        note: "Background Intelligent Transfer — used by Windows Update",
    },
    KnownService {
        name: "bthavctpsvc",
        safety: "caution",
        category: "bluetooth",
        note: "AVCTP service for Bluetooth audio",
    },
    KnownService {
        name: "bthserv",
        safety: "caution",
        category: "bluetooth",
        note: "Bluetooth Support Service — needed for Bluetooth devices",
    },
    KnownService {
        name: "cdpsvc",
        safety: "caution",
        category: "telemetry",
        note: "Connected Devices Platform — used by Timeline and device sync",
    },
    KnownService {
        name: "cdpusersvc",
        safety: "caution",
        category: "telemetry",
        note: "Connected Devices Platform per-user service",
    },
    KnownService {
        name: "cryptsvc",
        safety: "unsafe",
        category: "security",
        note: "Cryptographic Services — required for signatures and certificates",
    },
    KnownService {
        name: "dcomlaunch",
        safety: "unsafe",
        category: "core",
        note: "DCOM Server Process Launcher — critical for COM+",
    },
    KnownService {
        name: "dhcp",
        safety: "unsafe",
        category: "network",
        note: "DHCP Client — required for automatic IP addressing",
    },
    KnownService {
        name: "diagsvc",
        safety: "safe",
        category: "telemetry",
        note: "Diagnostic Execution Service",
    },
    KnownService {
        name: "diagsystemhost",
        safety: "safe",
        category: "telemetry",
        note: "Diagnostic System Host",
    },
    KnownService {
        name: "diagtrack",
        safety: "safe",
        category: "telemetry",
        note: "Connected User Experiences and Telemetry",
    },
    KnownService {
        name: "dmwappushservice",
        safety: "safe",
        category: "telemetry",
        note: "WAP Push Message Routing for telemetry",
    },
    KnownService {
        name: "dmwappushsvc",
        safety: "safe",
        category: "telemetry",
        note: "WAP Push Message Routing (alternate name)",
    },
    KnownService {
        name: "dnscache",
        safety: "unsafe",
        category: "network",
        note: "DNS Client — required for name resolution",
    },
    KnownService {
        name: "eventlog",
        safety: "unsafe",
        category: "core",
        note: "Windows Event Log — needed for diagnostics and auditing",
    },
    KnownService {
        name: "fax",
        safety: "safe",
        category: "fax",
        note: "Fax service",
    },
    KnownService {
        name: "hvhost",
        safety: "caution",
        category: "hyper-v",
        note: "HV Host Service",
    },
    KnownService {
        name: "icssvc",
        safety: "safe",
        category: "network",
        note: "Windows Mobile Hotspot Service",
    },
    KnownService {
        name: "lanmanserver",
        safety: "unsafe",
        category: "network",
        note: "Server service — required for file sharing",
    },
    KnownService {
        name: "lanmanworkstation",
        safety: "unsafe",
        category: "network",
        note: "Workstation service — required for network resource access",
    },
    KnownService {
        name: "lfsvc",
        safety: "safe",
        category: "telemetry",
        note: "Geolocation Service",
    },
    KnownService {
        name: "lsm",
        safety: "unsafe",
        category: "core",
        note: "Local Session Manager — required for session management",
    },
    KnownService {
        name: "mapsbroker",
        safety: "safe",
        category: "misc",
        note: "Downloaded Maps Manager",
    },
    KnownService {
        name: "mpssvc",
        safety: "unsafe",
        category: "security",
        note: "Windows Defender Firewall — network protection",
    },
    KnownService {
        name: "netprofm",
        safety: "unsafe",
        category: "network",
        note: "Network List Service — required for network management",
    },
    KnownService {
        name: "nlasvc",
        safety: "unsafe",
        category: "network",
        note: "Network Location Awareness — required for network detection",
    },
    KnownService {
        name: "nsi",
        safety: "unsafe",
        category: "network",
        note: "Network Store Interface — required for network connectivity",
    },
    KnownService {
        name: "onesyncsvc",
        safety: "caution",
        category: "misc",
        note: "Sync Host — used by Mail, Calendar, Contacts",
    },
    KnownService {
        name: "pcasvc",
        safety: "safe",
        category: "misc",
        note: "Program Compatibility Assistant",
    },
    KnownService {
        name: "phonesvc",
        safety: "caution",
        category: "misc",
        note: "Phone Service — required by some wireless headset dongles, including Audeze Maxwell",
    },
    KnownService {
        name: "plugplay",
        safety: "unsafe",
        category: "core",
        note: "Plug and Play — required for device detection",
    },
    KnownService {
        name: "power",
        safety: "unsafe",
        category: "core",
        note: "Power service — required for power management",
    },
    KnownService {
        name: "printnotify",
        safety: "caution",
        category: "print",
        note: "Printer Extensions and Notifications",
    },
    KnownService {
        name: "profsvc",
        safety: "unsafe",
        category: "core",
        note: "User Profile Service — required for login",
    },
    KnownService {
        name: "remoteaccess",
        safety: "safe",
        category: "remote",
        note: "Routing and Remote Access",
    },
    KnownService {
        name: "remoteregistry",
        safety: "safe",
        category: "remote",
        note: "Remote Registry",
    },
    KnownService {
        name: "retaildemo",
        safety: "safe",
        category: "misc",
        note: "Retail Demo Service",
    },
    KnownService {
        name: "rpcss",
        safety: "unsafe",
        category: "core",
        note: "Remote Procedure Call — critical for Windows operation",
    },
    KnownService {
        name: "samss",
        safety: "unsafe",
        category: "security",
        note: "Security Accounts Manager — required for authentication",
    },
    KnownService {
        name: "schedule",
        safety: "unsafe",
        category: "core",
        note: "Task Scheduler — used by many Windows components",
    },
    KnownService {
        name: "seclogon",
        safety: "safe",
        category: "misc",
        note: "Secondary Logon (Run As)",
    },
    KnownService {
        name: "securityhealthservice",
        safety: "unsafe",
        category: "security",
        note: "Windows Security Center",
    },
    KnownService {
        name: "sessionenv",
        safety: "caution",
        category: "remote",
        note: "Remote Desktop Configuration",
    },
    KnownService {
        name: "sharedaccess",
        safety: "safe",
        category: "network",
        note: "Internet Connection Sharing",
    },
    KnownService {
        name: "spooler",
        safety: "caution",
        category: "print",
        note: "Print Spooler — needed if you use a printer",
    },
    KnownService {
        name: "sppsvc",
        safety: "unsafe",
        category: "core",
        note: "Software Protection Platform — Windows activation",
    },
    KnownService {
        name: "sshd",
        safety: "caution",
        category: "developer",
        note: "OpenSSH SSH Server",
    },
    KnownService {
        name: "sysmain",
        safety: "caution",
        category: "misc",
        note: "Superfetch/SysMain — safe on SSDs, may slow HDDs",
    },
    KnownService {
        name: "tabletinputservice",
        safety: "safe",
        category: "misc",
        note: "Touch Keyboard and Handwriting — safe if no touch screen",
    },
    KnownService {
        name: "termservice",
        safety: "caution",
        category: "remote",
        note: "Remote Desktop Services — needed for RDP",
    },
    KnownService {
        name: "themes",
        safety: "caution",
        category: "misc",
        note: "Disabling removes theme support and visual styles",
    },
    KnownService {
        name: "trustedinstaller",
        safety: "unsafe",
        category: "core",
        note: "Windows Modules Installer — required for updates",
    },
    KnownService {
        name: "umrdpservice",
        safety: "caution",
        category: "remote",
        note: "Remote Desktop Services UserMode Port Redirector",
    },
    KnownService {
        name: "vmcompute",
        safety: "caution",
        category: "hyper-v",
        note: "Hyper-V Host Compute Service",
    },
    KnownService {
        name: "vmms",
        safety: "caution",
        category: "hyper-v",
        note: "Hyper-V Virtual Machine Management",
    },
    KnownService {
        name: "wbiosrvc",
        safety: "safe",
        category: "misc",
        note: "Windows Biometric Service — safe if no fingerprint reader",
    },
    KnownService {
        name: "wersvc",
        safety: "safe",
        category: "telemetry",
        note: "Windows Error Reporting",
    },
    KnownService {
        name: "windefend",
        safety: "unsafe",
        category: "security",
        note: "Windows Defender Antivirus — primary system protection",
    },
    KnownService {
        name: "winmgmt",
        safety: "unsafe",
        category: "core",
        note: "Windows Management Instrumentation — widely depended on",
    },
    KnownService {
        name: "wisvc",
        safety: "safe",
        category: "misc",
        note: "Windows Insider Service",
    },
    KnownService {
        name: "wmpnetworksvc",
        safety: "safe",
        category: "media",
        note: "Windows Media Player Network Sharing",
    },
    KnownService {
        name: "wpnservice",
        safety: "caution",
        category: "misc",
        note: "Windows Push Notifications — needed for app notifications",
    },
    KnownService {
        name: "wpnuserservice",
        safety: "caution",
        category: "misc",
        note: "Windows Push Notifications per-user service",
    },
    KnownService {
        name: "wsearch",
        safety: "caution",
        category: "misc",
        note: "Windows Search — disabling removes file indexing and search",
    },
    KnownService {
        name: "wuauserv",
        safety: "unsafe",
        category: "core",
        note: "Windows Update — required to receive security patches",
    },
    KnownService {
        name: "xblauthmanager",
        safety: "caution",
        category: "xbox",
        note: "Xbox Live Auth Manager — needed for Xbox/Game Pass",
    },
    KnownService {
        name: "xblgamesave",
        safety: "caution",
        category: "xbox",
        note: "Xbox Live Game Save — needed for cloud saves",
    },
    KnownService {
        name: "xboxgipsvc",
        safety: "caution",
        category: "xbox",
        note: "Xbox Accessory Management — needed for Xbox controllers",
    },
    KnownService {
        name: "xboxnetapisvc",
        safety: "caution",
        category: "xbox",
        note: "Xbox Live Networking Service — needed for Xbox online features",
    },
];

/// Look a service up by name.
///
/// Per-user service instances carry a suffix (`CDPUserSvc_a1b2c3`); the suffix is
/// stripped before matching, which is how Windows itself groups them.
pub fn lookup(name: &str) -> Option<&'static KnownService> {
    let lowered = name.trim().to_ascii_lowercase();
    let base = match lowered.rsplit_once('_') {
        Some((head, suffix))
            if !suffix.is_empty() && suffix.chars().all(|c| c.is_ascii_hexdigit()) =>
        {
            head
        }
        _ => lowered.as_str(),
    };
    KNOWN_SERVICES.iter().find(|s| s.name == base)
}

/// Is this a service name Windows itself ships?
pub fn is_known(name: &str) -> bool {
    lookup(name).is_some()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_is_populated_and_sorted_without_duplicates() {
        assert!(
            KNOWN_SERVICES.len() >= 60,
            "expected the full vendored table, found {}",
            KNOWN_SERVICES.len()
        );
        let mut names: Vec<&str> = KNOWN_SERVICES.iter().map(|s| s.name).collect();
        let before = names.len();
        names.sort_unstable();
        names.dedup();
        assert_eq!(before, names.len(), "duplicate service name in the table");
        assert!(KNOWN_SERVICES
            .iter()
            .all(|s| s.name == s.name.to_lowercase()));
        assert!(KNOWN_SERVICES.iter().all(|s| !s.safety.is_empty()));
    }

    #[test]
    fn lookup_is_case_insensitive() {
        assert!(lookup("DiagTrack").is_some());
        assert!(lookup("diagtrack").is_some());
        assert!(lookup("  diagtrack  ").is_some());
    }

    #[test]
    fn per_user_suffixes_are_stripped() {
        // Windows appends _<hex> to per-user instances; the base name is the service.
        let base = lookup("diagtrack");
        assert!(base.is_some());
        let with_suffix = lookup("DiagTrack_3f2a1b");
        assert_eq!(
            with_suffix.map(|s| s.name),
            base.map(|s| s.name),
            "a hex suffix must be stripped"
        );
    }

    #[test]
    fn a_suffix_that_is_not_hex_is_not_stripped() {
        // "irscan_not_a_service" must not silently collapse onto a real service.
        assert!(lookup("irscan_not_a_service").is_none());
    }

    #[test]
    fn unknown_names_return_none_instead_of_a_guess() {
        assert!(lookup("").is_none());
        assert!(lookup("definitely-not-a-windows-service").is_none());
        assert!(!is_known("definitely-not-a-windows-service"));
        assert!(is_known("diagtrack"));
    }

    #[test]
    fn every_entry_carries_a_note_and_a_known_safety_value() {
        for service in KNOWN_SERVICES {
            assert!(
                service.safety == "safe"
                    || service.safety == "caution"
                    || service.safety == "unsafe",
                "unexpected safety value {:?} for {}",
                service.safety,
                service.name
            );
            assert!(
                !service.note.is_empty(),
                "missing note for {}",
                service.name
            );
        }
    }
}
