// @generated by tools/gen_remote_tools.py from
// raw/WithSecureLabs__chainsaw/rules/evtx/service_installation/remote_access_tools.yml
// Source: WithSecureLabs/chainsaw (GPL-3.0). Data only - see THIRD_PARTY_NOTICES.md.
//
// Do not edit by hand: regenerate with `python tools/gen_remote_tools.py`.

//! Names remote-access tools register themselves under.
//!
//! The signature database describes products by the names of their files, which a
//! rename defeats. A service registration cannot be renamed so easily: the name is
//! what the installer chose and what the Service Control Manager records, and it
//! survives the binary being replaced. These lists give the 7045 check something to
//! match on that the file name cannot take away.

/// Service names observed for remote-access tools (33).
///
/// Matched case-insensitively as a substring, because installers pad these names.
pub const REMOTE_TOOL_SERVICE_NAMES: &[&str] = &[
    "ammyy",
    "anydesk",
    "atera",
    "chrome remote desktop",
    "client32",
    "gateway32",
    "goto resolve",
    "gotoassist",
    "gotomypc",
    "jumpcloud",
    "lmiguardiansvc",
    "logmein",
    "mesh agent",
    "meshcentral",
    "monblanking",
    "n-central take control service",
    "n-central take control updater service",
    "nskbfltr",
    "parsec",
    "pcanywhere",
    "realvnc",
    "remote utilities - host",
    "remotepc performance service",
    "rpcservice",
    "screenconnect",
    "splashtop",
    "supremo",
    "teamviewer",
    "tightvnc",
    "ultraviewer",
    "viewerservice",
    "vpdagent",
    "zoho assist",
];

/// Image names observed for remote-access tools (39).
///
/// The file-name part of each, lowercased: the directory an installer chooses varies
/// with the version and the vendor's habits, while the executable name does not.
pub const REMOTE_TOOL_IMAGES: &[&str] = &[
    "aa_v3.exe",
    "anydesk.exe",
    "ateraagent.exe",
    "awhost32.exe",
    "basupsrvc.exe",
    "basupsrvcupdater.exe",
    "client32.exe",
    "g2ax_service.exe",
    "g2r-updater.exe",
    "g2svc.exe",
    "gateway32.exe",
    "jumpcloud-agent.exe",
    "lmiguardiansvc.exe",
    "lmiinfo.sys",
    "lmirfsdriver.sys",
    "logmein.exe",
    "meshagent.exe",
    "meshcentral.exe",
    "monblanking.sys",
    "nskbfltr.sys",
    "openhardwaremonitorlib.sys",
    "pservice.exe",
    "ramaint.exe",
    "remotepcservice.exe",
    "remoting_host.exe",
    "rpcperformanceservice.exe",
    "rutserv.exe",
    "screenconnect.clientservice.exe",
    "srservice.exe",
    "ssuservice.exe",
    "supremoservice.exe",
    "supremosystem.exe",
    "teamviewer_service.exe",
    "tvnserver.exe",
    "ultraviewer_service.exe",
    "viewerservice.exe",
    "vncserver.exe",
    "vpdagent.exe",
    "zohoursservice.exe",
];
