#!/usr/bin/env python3
"""Generate `ir-recon/src/remote_tools.rs` from the chainsaw 7045 rules.

Why this data, and why it is worth a generator:

The signature database is built from LOLRMM, which describes each product by the names of
its *files*. That works, but a file name is easy to change - a renamed agent keeps its
service registration, because a service must be registered under a name. The event we
already read, 7045 (`Service Control Manager` service install), carries that name verbatim.

Measured before this file existed: the generated signature database held 708 ProcessName
needles and exactly **1** ServiceName needle. So a remote-access tool that installed itself
as a service under a name we had never seen was invisible to the 7045 check, even though the
instrumentation to see it was already in place.

Source: raw/WithSecureLabs__chainsaw/rules/evtx/service_installation/remote_access_tools.yml
(WithSecureLabs/chainsaw, GPL-3.0). Only the *data* is taken - two literal lists of
strings; no engine or code is copied, and the lists are re-emitted in this project's own
format. Permitted under the licence decision recorded in THIRD_PARTY_NOTICES.md, and
recorded there.

Determinism: the output is sorted and contains no timestamps, so regenerating it produces a
byte-identical file. tools/check_generated.sh verifies that.

Usage:
    python tools/gen_remote_tools.py            # write the file
    python tools/gen_remote_tools.py --check    # exit 1 if the file would change
"""

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SOURCE = (
    REPO
    / "raw/WithSecureLabs__chainsaw/rules/evtx/service_installation/remote_access_tools.yml"
)
OUT = REPO / "ir-recon/src/remote_tools.rs"


def gather(text, field):
    """Return the literal needles under `field`, normalised.

    The upstream form is a chainsaw pattern such as `i*AnyDesk*` (the `i` prefix means
    case-insensitive, `*` is a wildcard). The bare text is kept and matched
    case-insensitively here, so the wildcards carry no information and are stripped rather
    than translated - translating them would invent a matching language this project does
    not have, and a wildcard language is exactly where a false match would hide.
    """
    start = text.find(field + ":")
    if start < 0:
        raise SystemExit("field %r not found in %s" % (field, SOURCE))
    rest = text[start + len(field) + 1 :]
    stop = re.search(r"\n  [a-z_]+:", rest)
    if stop:
        rest = rest[: stop.start()]
    out = []
    for raw in re.findall(r"- '([^']+)'", rest):
        value = raw.lstrip("i").replace("*", "").strip()
        # A fingerprint shorter than three characters would match a large fraction of the
        # services on any machine, so it is dropped rather than allowed to generate noise.
        if len(value) >= 3:
            out.append(value.lower())
    return sorted(set(out))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not SOURCE.exists():
        raise SystemExit("missing source: %s" % SOURCE)

    text = SOURCE.read_text(encoding="utf-8", errors="replace")
    services = gather(text, "service_name")
    images = gather(text, "image_path")

    body = [
        "// @generated by tools/gen_remote_tools.py from",
        "// raw/WithSecureLabs__chainsaw/rules/evtx/service_installation/remote_access_tools.yml",
        "// Source: WithSecureLabs/chainsaw (GPL-3.0). Data only - see THIRD_PARTY_NOTICES.md.",
        "//",
        "// Do not edit by hand: regenerate with `python tools/gen_remote_tools.py`.",
        "",
        "//! Names remote-access tools register themselves under.",
        "//!",
        "//! The signature database describes products by the names of their files, which a",
        "//! rename defeats. A service registration cannot be renamed so easily: the name is",
        "//! what the installer chose and what the Service Control Manager records, and it",
        "//! survives the binary being replaced. These lists give the 7045 check something to",
        "//! match on that the file name cannot take away.",
        "",
        "/// Service names observed for remote-access tools (%d)." % len(services),
        "///",
        "/// Matched case-insensitively as a substring, because installers pad these names.",
        "pub const REMOTE_TOOL_SERVICE_NAMES: &[&str] = &[",
    ]
    body += ['    "%s",' % s for s in services]
    body += [
        "];",
        "",
        "/// Image names observed for remote-access tools (%d)." % len(images),
        "///",
        "/// The file-name part of each, lowercased: the directory an installer chooses varies",
        "/// with the version and the vendor's habits, while the executable name does not.",
        "pub const REMOTE_TOOL_IMAGES: &[&str] = &[",
    ]
    body += ['    "%s",' % i for i in images]
    body += ["];", ""]

    rendered = "\n".join(body)

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != rendered:
            print("CHANGED: %s is out of date" % OUT, file=sys.stderr)
            return 1
        print("OK: %s is up to date" % OUT.name)
        return 0

    OUT.write_text(rendered, encoding="utf-8", newline="\n")
    print("wrote %s: %d service names, %d images" % (OUT.relative_to(REPO), len(services), len(images)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
