#!/usr/bin/env python3
"""Generate ir-recon/src/known_services.rs from the kudu service-safety knowledge base.

Why a generator: the source is a TypeScript object literal, and transcribing 72
entries by hand invites exactly the kind of typo that turns a security tool into a
liar. This script is deterministic and re-runnable, and its output is checked in so
the build needs no Python.

Source: raw/AdventDevInc__kudu/src/shared/service-safety-kb.ts
Upstream: https://github.com/AdventDevInc/kudu (MIT). See THIRD_PARTY_NOTICES.md.
`raw/` is excluded from version control, so this is a vendoring step run by hand when
the upstream file changes - it is not part of the build.
"""

import pathlib
import re
import sys

SOURCE = pathlib.Path("raw/AdventDevInc__kudu/src/shared/service-safety-kb.ts")
DEST = pathlib.Path("ir-recon/src/known_services.rs")

# name: { safety: 'x', category: 'y', note: '...' } - notes may contain escaped quotes.
ENTRY = re.compile(
    r"^\s{2}(?P<name>[A-Za-z0-9]+):\s*\{\s*"
    r"safety:\s*'(?P<safety>[a-z]+)',\s*"
    r"category:\s*'(?P<category>[a-z-]+)',\s*"
    r"note:\s*'(?P<note>(?:[^'\\]|\\.)*)'",
    re.MULTILINE,
)

HEADER = """// @generated by tools/gen_known_services.py - DO NOT EDIT BY HAND.
//
// Source: AdventDevInc/kudu, src/shared/service-safety-kb.ts (MIT licence).
// Upstream: https://github.com/AdventDevInc/kudu
// See THIRD_PARTY_NOTICES.md for the attribution and the licence text.
//
// What this is for: a service Windows itself ships should not be reported merely
// because its image is unsigned, unreadable or absent. Those are normal states for a
// system service, and reporting them buries the services that are genuinely worth
// looking at.
"""

TAIL = """
/// Look a service up by name.
///
/// Per-user service instances carry a suffix (`CDPUserSvc_a1b2c3`); the suffix is
/// stripped before matching, which is how Windows itself groups them.
pub fn lookup(name: &str) -> Option<&'static KnownService> {
    let lowered = name.trim().to_ascii_lowercase();
    let base = match lowered.rsplit_once('_') {
        Some((head, suffix))
            if !suffix.is_empty() && suffix.chars().all(|c| c.is_ascii_hexdigit()) =>
        {
            head
        }
        _ => lowered.as_str(),
    };
    KNOWN_SERVICES.iter().find(|s| s.name == base)
}

/// Is this a service name Windows itself ships?
pub fn is_known(name: &str) -> bool {
    lookup(name).is_some()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_is_populated_and_sorted_without_duplicates() {
        assert!(
            KNOWN_SERVICES.len() >= 60,
            "expected the full vendored table, found {}",
            KNOWN_SERVICES.len()
        );
        let mut names: Vec<&str> = KNOWN_SERVICES.iter().map(|s| s.name).collect();
        let before = names.len();
        names.sort_unstable();
        names.dedup();
        assert_eq!(before, names.len(), "duplicate service name in the table");
        assert!(KNOWN_SERVICES
            .iter()
            .all(|s| s.name == s.name.to_lowercase()));
        assert!(KNOWN_SERVICES.iter().all(|s| !s.safety.is_empty()));
    }

    #[test]
    fn lookup_is_case_insensitive() {
        assert!(lookup("DiagTrack").is_some());
        assert!(lookup("diagtrack").is_some());
        assert!(lookup("  diagtrack  ").is_some());
    }

    #[test]
    fn per_user_suffixes_are_stripped() {
        // Windows appends _<hex> to per-user instances; the base name is the service.
        let base = lookup("diagtrack");
        assert!(base.is_some());
        let with_suffix = lookup("DiagTrack_3f2a1b");
        assert_eq!(
            with_suffix.map(|s| s.name),
            base.map(|s| s.name),
            "a hex suffix must be stripped"
        );
    }

    #[test]
    fn a_suffix_that_is_not_hex_is_not_stripped() {
        // "irscan_not_a_service" must not silently collapse onto a real service.
        assert!(lookup("irscan_not_a_service").is_none());
    }

    #[test]
    fn unknown_names_return_none_instead_of_a_guess() {
        assert!(lookup("").is_none());
        assert!(lookup("definitely-not-a-windows-service").is_none());
        assert!(!is_known("definitely-not-a-windows-service"));
        assert!(is_known("diagtrack"));
    }

    #[test]
    fn every_entry_carries_a_note_and_a_known_safety_value() {
        for service in KNOWN_SERVICES {
            assert!(
                service.safety == "safe"
                    || service.safety == "caution"
                    || service.safety == "unsafe",
                "unexpected safety value {:?} for {}",
                service.safety,
                service.name
            );
            assert!(
                !service.note.is_empty(),
                "missing note for {}",
                service.name
            );
        }
    }
}
"""


def rust_string(value: str) -> str:
    out = []
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        else:
            out.append(ch)
    return "".join(out)


def main() -> int:
    if SOURCE.exists() is False:
        print(f"source not found: {SOURCE}", file=sys.stderr)
        return 1

    text = SOURCE.read_text(encoding="utf-8")
    entries = ENTRY.findall(text)
    if len(entries) < 60:
        print(
            f"only parsed {len(entries)} entries - the source format changed",
            file=sys.stderr,
        )
        return 1

    seen = set()
    rows = []
    for name, safety, category, note in entries:
        key = name.lower()
        if key in seen:
            continue
        seen.add(key)
        unescaped = note.replace("\\'", "'").replace("\\\\", "\\")
        rows.append((key, safety, category, unescaped))

    rows.sort()

    body = []
    body.append("/// One Windows service that Windows itself ships.")
    body.append("pub struct KnownService {")
    body.append("    pub name: &'static str,")
    body.append("    /// `safe` (commonly disabled without issues), `caution`, or `unsafe`")
    body.append("    /// (system-critical).")
    body.append("    pub safety: &'static str,")
    body.append("    pub category: &'static str,")
    body.append("    pub note: &'static str,")
    body.append("}")
    body.append("")
    body.append(f"/// {len(rows)} entries, sorted by service name.")
    body.append("pub static KNOWN_SERVICES: &[KnownService] = &[")
    for name, safety, category, note in rows:
        body.append(
            '    KnownService { name: "%s", safety: "%s", category: "%s", note: "%s" },'
            % (
                rust_string(name),
                rust_string(safety),
                rust_string(category),
                rust_string(note),
            )
        )
    body.append("];")
    body.append("")

    DEST.write_text(
        HEADER + "\n".join(body) + "\n" + TAIL, encoding="utf-8", newline="\n"
    )
    print(f"wrote {DEST} with {len(rows)} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
